/*
 * LISTA DE PRESENTES — edite só o que está entre as chaves.
 *
 * - valor em reais (ponto nos centavos: 89.9 = R$ 89,90)
 * - id único, só minúsculas, números e hífen; não mude o id de um presente que já recebeu pagamento
 * - foto: imagem quadrada com fundo branco (600 x 600 px) na pasta images/presentes; sem foto, aparece um ícone
 * - descricao (opcional): uma frase curta embaixo do nome
 * - "oculto": true tira da lista sem apagar; "somentePix": true bloqueia o cartão no item
 * - a ordem aqui é a ordem em que os presentes aparecem na página
 *
 * Este arquivo é lido pela página e pelo servidor (o servidor cobra sempre o valor daqui).
 */
(function (lista) {
  if (typeof module === 'object' && module.exports) module.exports = lista;
  else window.LISTA_DE_PRESENTES = lista;
})({
  "valorLivre": {
    "ativo": true,
    "minimo": 20,
    "maximo": 10000,
    "sugestoes": [50, 100, 200, 500]
  },
  "cartao": {
    "ativo": true,
    "valorMinimo": 20,
    "maxParcelas": 12
  },
  "categorias": [
    {"id": "lua-de-mel", "nome": "Lua de mel", "descricao": "Para a nossa primeira viagem como casados."},
    {"id": "mesa", "nome": "Mesa posta", "descricao": "Para receber a família e os amigos."},
    {"id": "cozinha", "nome": "Cozinha", "descricao": "Para cozinhar juntos."},
    {"id": "churrasco", "nome": "Churrasco", "descricao": "Para os domingos com a família e os amigos."},
    {"id": "eletros", "nome": "Eletrodomésticos", "descricao": "Para o dia a dia da casa."},
    {"id": "tecnologia", "nome": "Tecnologia e lazer", "descricao": "Para descansar e se divertir juntos."},
    {"id": "sala", "nome": "Sala e decoração", "descricao": "Para deixar a casa com a nossa cara."},
    {"id": "quarto", "nome": "Quarto e banho", "descricao": "Para o descanso e os cuidados de cada dia."},
    {"id": "casa", "nome": "Casa", "descricao": "Para organizar e cuidar da casa."},
    {"id": "divertidos", "nome": "Divertidos", "descricao": "Para rir e ajudar no começo da vida a dois."}
  ],
  "presentes": [
    {"id": "ldm-cartoes-postais", "categoria": "lua-de-mel", "nome": "Cartões-postais para a família", "valor": 40, "foto": "images/presentes/ldm-cartoes-postais.webp"},
    {"id": "ldm-agua-de-coco", "categoria": "lua-de-mel", "nome": "Água de coco na praia", "valor": 50, "foto": "images/presentes/ldm-agua-de-coco.webp"},
    {"id": "ldm-sorvete", "categoria": "lua-de-mel", "nome": "Sorvete todos os dias da viagem", "valor": 80, "foto": "images/presentes/ldm-sorvete.webp"},
    {"id": "ldm-roda-gigante", "categoria": "lua-de-mel", "nome": "Volta na roda-gigante", "valor": 90, "foto": "images/presentes/ldm-roda-gigante.webp"},
    {"id": "ldm-bicicletas", "categoria": "lua-de-mel", "nome": "Bicicletas por um dia", "valor": 90, "foto": "images/presentes/ldm-bicicletas.webp"},
    {"id": "ldm-chip-internet", "categoria": "lua-de-mel", "nome": "Internet no celular durante a viagem", "valor": 90, "foto": "images/presentes/ldm-chip-internet.webp"},
    {"id": "ldm-gorjetas", "categoria": "lua-de-mel", "nome": "As gorjetas da viagem", "valor": 100, "foto": "images/presentes/ldm-gorjetas.webp"},
    {"id": "ldm-kit-viagem", "categoria": "lua-de-mel", "nome": "Necessaire nova para a viagem", "valor": 120, "foto": "images/presentes/ldm-kit-viagem.webp"},
    {"id": "ldm-assentos-juntos", "categoria": "lua-de-mel", "nome": "Assentos lado a lado no avião", "valor": 120, "foto": "images/presentes/ldm-assentos-juntos.webp"},
    {"id": "ldm-stand-up", "categoria": "lua-de-mel", "nome": "Aula de stand up paddle", "valor": 140, "foto": "images/presentes/ldm-stand-up.webp"},
    {"id": "ldm-museus", "categoria": "lua-de-mel", "nome": "Ingressos para museus", "valor": 140, "foto": "images/presentes/ldm-museus.webp"},
    {"id": "ldm-degustacao-chocolates", "categoria": "lua-de-mel", "nome": "Degustação de chocolates", "valor": 140, "foto": "images/presentes/ldm-degustacao-chocolates.webp"},
    {"id": "ldm-cafe-na-cama", "categoria": "lua-de-mel", "nome": "Café da manhã na cama", "valor": 150, "foto": "images/presentes/ldm-cafe-na-cama.webp"},
    {"id": "ldm-tirolesa", "categoria": "lua-de-mel", "nome": "Tirolesa com vista para o mar", "valor": 150, "foto": "images/presentes/ldm-tirolesa.webp"},
    {"id": "ldm-aula-danca", "categoria": "lua-de-mel", "nome": "Aula de dança a dois", "valor": 150, "foto": "images/presentes/ldm-aula-danca.webp"},
    {"id": "ldm-lembrancinhas", "categoria": "lua-de-mel", "nome": "Lembrancinhas da viagem", "valor": 150, "foto": "images/presentes/ldm-lembrancinhas.webp"},
    {"id": "ldm-kit-praia", "categoria": "lua-de-mel", "nome": "Kit praia para a viagem", "valor": 160, "foto": "images/presentes/ldm-kit-praia.webp"},
    {"id": "ldm-caiaque", "categoria": "lua-de-mel", "nome": "Passeio de caiaque a dois", "valor": 160, "foto": "images/presentes/ldm-caiaque.webp"},
    {"id": "ldm-aquario", "categoria": "lua-de-mel", "nome": "Ingressos para o aquário", "valor": 160, "foto": "images/presentes/ldm-aquario.webp"},
    {"id": "ldm-cafe-da-tarde", "categoria": "lua-de-mel", "nome": "Um café da tarde especial", "valor": 160, "foto": "images/presentes/ldm-cafe-da-tarde.webp"},
    {"id": "ldm-drinks-por-do-sol", "categoria": "lua-de-mel", "nome": "Drinks sem álcool ao pôr do sol", "valor": 180, "foto": "images/presentes/ldm-drinks-por-do-sol.webp"},
    {"id": "ldm-trilha-cachoeira", "categoria": "lua-de-mel", "nome": "Trilha até uma cachoeira", "valor": 180, "foto": "images/presentes/ldm-trilha-cachoeira.webp"},
    {"id": "ldm-arvorismo", "categoria": "lua-de-mel", "nome": "Arvorismo na mata", "valor": 180, "foto": "images/presentes/ldm-arvorismo.webp"},
    {"id": "ldm-teleferico", "categoria": "lua-de-mel", "nome": "Passeio de teleférico", "valor": 180, "foto": "images/presentes/ldm-teleferico.webp"},
    {"id": "ldm-transfer", "categoria": "lua-de-mel", "nome": "Transfer do aeroporto ao hotel", "valor": 190, "foto": "images/presentes/ldm-transfer.webp"},
    {"id": "ldm-estrelas", "categoria": "lua-de-mel", "nome": "Noite de observação de estrelas", "valor": 200, "foto": "images/presentes/ldm-estrelas.webp"},
    {"id": "ldm-city-tour", "categoria": "lua-de-mel", "nome": "City tour pela cidade", "valor": 200, "foto": "images/presentes/ldm-city-tour.webp"},
    {"id": "ldm-cavalgada", "categoria": "lua-de-mel", "nome": "Cavalgada na praia", "valor": 220, "foto": "images/presentes/ldm-cavalgada.webp"},
    {"id": "ldm-piquenique", "categoria": "lua-de-mel", "nome": "Piquenique na praia", "valor": 240, "foto": "images/presentes/ldm-piquenique.webp"},
    {"id": "ldm-rafting", "categoria": "lua-de-mel", "nome": "Rafting nas corredeiras", "valor": 240, "foto": "images/presentes/ldm-rafting.webp"},
    {"id": "ldm-bagagem-extra", "categoria": "lua-de-mel", "nome": "Bagagem extra no voo", "valor": 250, "foto": "images/presentes/ldm-bagagem-extra.webp"},
    {"id": "ldm-carro-alugado", "categoria": "lua-de-mel", "nome": "Um dia de carro alugado", "valor": 260, "foto": "images/presentes/ldm-carro-alugado.webp"},
    {"id": "ldm-aula-surf", "categoria": "lua-de-mel", "nome": "Aula de surf", "valor": 260, "foto": "images/presentes/ldm-aula-surf.webp"},
    {"id": "ldm-luau", "categoria": "lua-de-mel", "nome": "Luau na praia", "valor": 260, "foto": "images/presentes/ldm-luau.webp"},
    {"id": "ldm-trem-turistico", "categoria": "lua-de-mel", "nome": "Passeio de trem turístico", "valor": 260, "foto": "images/presentes/ldm-trem-turistico.webp"},
    {"id": "ldm-seguro-viagem", "categoria": "lua-de-mel", "nome": "Seguro viagem", "valor": 280, "foto": "images/presentes/ldm-seguro-viagem.webp"},
    {"id": "ldm-buggy", "categoria": "lua-de-mel", "nome": "Passeio de buggy nas dunas", "valor": 280, "foto": "images/presentes/ldm-buggy.webp"},
    {"id": "ldm-tour-gastronomico", "categoria": "lua-de-mel", "nome": "Tour gastronômico pela cidade", "valor": 280, "foto": "images/presentes/ldm-tour-gastronomico.webp"},
    {"id": "ldm-frutos-do-mar", "categoria": "lua-de-mel", "nome": "Almoço de frutos do mar", "valor": 280, "foto": "images/presentes/ldm-frutos-do-mar.webp"},
    {"id": "ldm-snorkel", "categoria": "lua-de-mel", "nome": "Mergulho com snorkel", "valor": 290, "foto": "images/presentes/ldm-snorkel.webp"},
    {"id": "ldm-parque-aquatico", "categoria": "lua-de-mel", "nome": "Um dia num parque aquático", "valor": 300, "foto": "images/presentes/ldm-parque-aquatico.webp"},
    {"id": "ldm-sala-vip", "categoria": "lua-de-mel", "nome": "Sala VIP no aeroporto", "valor": 300, "foto": "images/presentes/ldm-sala-vip.webp"},
    {"id": "ldm-passeio-barco", "categoria": "lua-de-mel", "nome": "Passeio de barco", "valor": 320, "foto": "images/presentes/ldm-passeio-barco.webp"},
    {"id": "ldm-jantar-romantico", "categoria": "lua-de-mel", "nome": "Jantar romântico", "valor": 350, "foto": "images/presentes/ldm-jantar-romantico.webp"},
    {"id": "ldm-pescaria", "categoria": "lua-de-mel", "nome": "Pescaria em alto-mar", "valor": 350, "foto": "images/presentes/ldm-pescaria.webp"},
    {"id": "ldm-massagem", "categoria": "lua-de-mel", "nome": "Massagem para dois", "valor": 380, "foto": "images/presentes/ldm-massagem.webp"},
    {"id": "ldm-jet-ski", "categoria": "lua-de-mel", "nome": "Passeio de jet ski", "valor": 380, "foto": "images/presentes/ldm-jet-ski.webp"},
    {"id": "ldm-show", "categoria": "lua-de-mel", "nome": "Ingressos para um show", "valor": 420, "foto": "images/presentes/ldm-show.webp"},
    {"id": "ldm-parapente", "categoria": "lua-de-mel", "nome": "Voo de parapente", "valor": 450, "foto": "images/presentes/ldm-parapente.webp"},
    {"id": "ldm-mala", "categoria": "lua-de-mel", "nome": "Mala de viagem nova", "valor": 450, "foto": "images/presentes/ldm-mala.webp"},
    {"id": "ldm-upgrade-quarto", "categoria": "lua-de-mel", "nome": "Upgrade para quarto com vista", "valor": 480, "foto": "images/presentes/ldm-upgrade-quarto.webp"},
    {"id": "ldm-dia-de-spa", "categoria": "lua-de-mel", "nome": "Dia de spa", "valor": 560, "foto": "images/presentes/ldm-dia-de-spa.webp"},
    {"id": "ldm-diaria-hotel", "categoria": "lua-de-mel", "nome": "Uma diária no hotel", "valor": 650, "foto": "images/presentes/ldm-diaria-hotel.webp"},
    {"id": "ldm-ensaio-fotos", "categoria": "lua-de-mel", "nome": "Ensaio de fotos na viagem", "valor": 800, "foto": "images/presentes/ldm-ensaio-fotos.webp"},
    {"id": "ldm-helicoptero", "categoria": "lua-de-mel", "nome": "Passeio de helicóptero", "valor": 950, "foto": "images/presentes/ldm-helicoptero.webp"},
    {"id": "ldm-passeio-balao", "categoria": "lua-de-mel", "nome": "Passeio de balão ao amanhecer", "valor": 1200, "foto": "images/presentes/ldm-passeio-balao.webp"},
    {"id": "ldm-passagem-noiva", "categoria": "lua-de-mel", "nome": "Passagem da noiva", "valor": 1500, "foto": "images/presentes/ldm-passagem-noiva.webp"},
    {"id": "ldm-passagem-noivo", "categoria": "lua-de-mel", "nome": "Passagem do noivo", "valor": 1500, "foto": "images/presentes/ldm-passagem-noivo.webp"},
    {"id": "ldm-tres-noites", "categoria": "lua-de-mel", "nome": "Três noites de hotel", "valor": 1950, "foto": "images/presentes/ldm-tres-noites.webp"},
    {"id": "ldm-vinho-e-queijos", "categoria": "lua-de-mel", "nome": "Vinho e queijos no hotel", "valor": 240, "foto": "images/presentes/ldm-vinho-e-queijos.webp", "oculto": true},
    {"id": "mesa-kit-bolo", "categoria": "mesa", "nome": "Espátula para servir bolo", "valor": 39.9, "foto": "images/presentes/mesa-kit-bolo.webp"},
    {"id": "mesa-pegador-salada", "categoria": "mesa", "nome": "Pegador de salada (2 peças)", "valor": 45.9, "foto": "images/presentes/mesa-pegador-salada.webp"},
    {"id": "tabua-de-frios", "categoria": "mesa", "nome": "Tábua de frios", "valor": 46.14, "foto": "images/presentes/tabua-de-frios.webp"},
    {"id": "mesa-molheira", "categoria": "mesa", "nome": "Molheira de porcelana", "valor": 49.9, "foto": "images/presentes/mesa-molheira.webp"},
    {"id": "mesa-manteigueira", "categoria": "mesa", "nome": "Manteigueira de madeira com tampa", "valor": 59.9, "foto": "images/presentes/mesa-manteigueira.webp"},
    {"id": "mesa-guardanapos", "categoria": "mesa", "nome": "Jogo de 4 guardanapos de tecido", "valor": 59.9, "foto": "images/presentes/mesa-guardanapos.webp"},
    {"id": "mesa-descanso-panela", "categoria": "mesa", "nome": "Descanso de panela de sisal", "valor": 59.9, "foto": "images/presentes/mesa-descanso-panela.webp"},
    {"id": "mesa-argolas", "categoria": "mesa", "nome": "Jogo de 4 argolas para guardanapo", "valor": 62.9, "foto": "images/presentes/mesa-argolas.webp"},
    {"id": "mesa-porta-copos", "categoria": "mesa", "nome": "Porta-copos (4 peças)", "valor": 62.9, "foto": "images/presentes/mesa-porta-copos.webp"},
    {"id": "mesa-porta-guardanapos", "categoria": "mesa", "nome": "Porta-guardanapos floral", "valor": 65.9, "foto": "images/presentes/mesa-porta-guardanapos.webp"},
    {"id": "mesa-acucareiro", "categoria": "mesa", "nome": "Açucareiro de porcelana", "valor": 69.9, "foto": "images/presentes/mesa-acucareiro.webp"},
    {"id": "mesa-pratinhos-aperitivo", "categoria": "mesa", "nome": "Jogo de 4 pratinhos para aperitivo", "valor": 69.9, "foto": "images/presentes/mesa-pratinhos-aperitivo.webp"},
    {"id": "jogo-americano", "categoria": "mesa", "nome": "Jogo americano (4 lugares)", "valor": 69.99, "foto": "images/presentes/jogo-americano.webp"},
    {"id": "mesa-caminho", "categoria": "mesa", "nome": "Caminho de mesa de fibra natural", "valor": 72.9, "foto": "images/presentes/mesa-caminho.webp"},
    {"id": "mesa-biscoiteira", "categoria": "mesa", "nome": "Biscoiteira", "valor": 72.9, "foto": "images/presentes/mesa-biscoiteira.webp"},
    {"id": "mesa-galheteiro", "categoria": "mesa", "nome": "Galheta de vidro para azeite", "valor": 79.9, "foto": "images/presentes/mesa-galheteiro.webp"},
    {"id": "mesa-cesta-paes", "categoria": "mesa", "nome": "Cesta de pães com tampa de tela", "valor": 79.9, "foto": "images/presentes/mesa-cesta-paes.webp"},
    {"id": "jarra-vidro", "categoria": "mesa", "nome": "Jarra de vidro", "valor": 89.9, "foto": "images/presentes/jarra-vidro.webp"},
    {"id": "sobremesa-viena", "categoria": "mesa", "nome": "Jogo de sobremesa Viena (vidro)", "valor": 90, "foto": "images/presentes/sobremesa-viena.webp"},
    {"id": "copos-cristal", "categoria": "mesa", "nome": "Par de copos de cristal", "valor": 99.9, "foto": "images/presentes/copos-cristal.webp"},
    {"id": "mesa-travessa-oval", "categoria": "mesa", "nome": "Travessa oval de cerâmica", "valor": 99.9, "foto": "images/presentes/mesa-travessa-oval.webp"},
    {"id": "mesa-queijeira", "categoria": "mesa", "nome": "Queijeira com tampa", "valor": 99.9, "foto": "images/presentes/mesa-queijeira.webp"},
    {"id": "mesa-fruteira", "categoria": "mesa", "nome": "Fruteira de mesa", "valor": 109.9, "foto": "images/presentes/mesa-fruteira.webp"},
    {"id": "mesa-tabua-pizza", "categoria": "mesa", "nome": "Tábua redonda para servir pizza", "valor": 109.9, "foto": "images/presentes/mesa-tabua-pizza.webp"},
    {"id": "sousplats", "categoria": "mesa", "nome": "Conjunto de sousplats", "valor": 111.6, "foto": "images/presentes/sousplats.webp"},
    {"id": "mesa-canecas", "categoria": "mesa", "nome": "Jogo de 4 canecas de cerâmica", "valor": 119.9, "foto": "images/presentes/mesa-canecas.webp"},
    {"id": "mesa-saladeira", "categoria": "mesa", "nome": "Saladeira de cerâmica", "valor": 119.9, "foto": "images/presentes/mesa-saladeira.webp"},
    {"id": "mesa-moringa", "categoria": "mesa", "nome": "Moringa de porcelana com copo", "valor": 119.9, "foto": "images/presentes/mesa-moringa.webp"},
    {"id": "conjunto-frios", "categoria": "mesa", "nome": "Conjunto para frios", "valor": 119.98, "foto": "images/presentes/conjunto-frios.webp"},
    {"id": "mesa-bowls", "categoria": "mesa", "nome": "Jogo de 3 bowls de porcelana", "valor": 129.9, "foto": "images/presentes/mesa-bowls.webp"},
    {"id": "mesa-centro-mesa", "categoria": "mesa", "nome": "Centro de mesa decorativo", "valor": 129.9, "foto": "images/presentes/mesa-centro-mesa.webp"},
    {"id": "xicaras-cafe", "categoria": "mesa", "nome": "Jogo de 4 xícaras de café", "valor": 139.9, "foto": "images/presentes/xicaras-cafe.webp"},
    {"id": "mesa-bandeja-servir", "categoria": "mesa", "nome": "Bandeja redonda de bambu", "valor": 139.9, "foto": "images/presentes/mesa-bandeja-servir.webp"},
    {"id": "mesa-casticais", "categoria": "mesa", "nome": "Candelabro dourado para 2 velas", "valor": 139.9, "foto": "images/presentes/mesa-casticais.webp"},
    {"id": "mesa-bule-cha", "categoria": "mesa", "nome": "Bule de chá de vidro com infusor", "valor": 149.9, "foto": "images/presentes/mesa-bule-cha.webp"},
    {"id": "mesa-bandeja-cama", "categoria": "mesa", "nome": "Bandeja com pés para café na cama", "valor": 149.9, "foto": "images/presentes/mesa-bandeja-cama.webp"},
    {"id": "mesa-tacas-sobremesa", "categoria": "mesa", "nome": "Jogo de 4 taças de sobremesa", "valor": 151.9, "foto": "images/presentes/mesa-tacas-sobremesa.webp"},
    {"id": "pratos-quadrados", "categoria": "mesa", "nome": "Jogo de pratos quadrados", "valor": 154, "foto": "images/presentes/pratos-quadrados.webp"},
    {"id": "toalha-mesa", "categoria": "mesa", "nome": "Toalha de mesa", "valor": 169.9, "foto": "images/presentes/toalha-mesa.webp"},
    {"id": "mesa-copos-altos", "categoria": "mesa", "nome": "Jogo de 6 copos altos", "valor": 169.9, "foto": "images/presentes/mesa-copos-altos.webp"},
    {"id": "balde-gelo", "categoria": "mesa", "nome": "Balde de gelo inox", "valor": 179.9, "foto": "images/presentes/balde-gelo.webp"},
    {"id": "tacas-espumante", "categoria": "mesa", "nome": "Jogo de taças para brinde", "valor": 179.9, "foto": "images/presentes/tacas-espumante.webp"},
    {"id": "mesa-moedores", "categoria": "mesa", "nome": "Par de moedores de sal e pimenta", "valor": 179.9, "foto": "images/presentes/mesa-moedores.webp"},
    {"id": "mesa-boleira", "categoria": "mesa", "nome": "Boleira de vidro com tampa", "valor": 199.9, "foto": "images/presentes/mesa-boleira.webp"},
    {"id": "comida-oriental", "categoria": "mesa", "nome": "Conjunto para comida oriental", "valor": 217.35, "foto": "images/presentes/comida-oriental.webp"},
    {"id": "mesa-sopeira", "categoria": "mesa", "nome": "Sopeira de porcelana com tampa", "valor": 259.9, "foto": "images/presentes/mesa-sopeira.webp"},
    {"id": "aparelho-fondue", "categoria": "mesa", "nome": "Aparelho de fondue", "valor": 259.9, "foto": "images/presentes/aparelho-fondue.webp"},
    {"id": "talheres-pizza", "categoria": "mesa", "nome": "Kit de talheres para pizza", "valor": 262, "foto": "images/presentes/talheres-pizza.webp"},
    {"id": "tacas-vinho", "categoria": "mesa", "nome": "Conjunto de taças de cristal", "valor": 299.9, "foto": "images/presentes/tacas-vinho.webp"},
    {"id": "petisqueira", "categoria": "mesa", "nome": "Petisqueira giratória de bambu", "valor": 320.14, "foto": "images/presentes/petisqueira.webp"},
    {"id": "aparelho-jantar-estampado", "categoria": "mesa", "nome": "Aparelho de jantar azul estampado", "valor": 399.9, "foto": "images/presentes/aparelho-jantar-estampado.webp"},
    {"id": "faqueiro-42", "categoria": "mesa", "nome": "Faqueiro 42 peças", "valor": 499.9, "foto": "images/presentes/faqueiro-42.webp"},
    {"id": "aparelho-jantar-azul", "categoria": "mesa", "nome": "Aparelho de jantar azul-claro", "valor": 559.9, "foto": "images/presentes/aparelho-jantar-azul.webp"},
    {"id": "mesa-carrinho-servir", "categoria": "mesa", "nome": "Carrinho de chá e café", "valor": 659.9, "foto": "images/presentes/mesa-carrinho-servir.webp"},
    {"id": "faqueiro-84", "categoria": "mesa", "nome": "Faqueiro 84 peças", "valor": 758, "foto": "images/presentes/faqueiro-84.webp"},
    {"id": "aparelho-jantar-dourado", "categoria": "mesa", "nome": "Aparelho de jantar com filete dourado", "valor": 1009.3, "foto": "images/presentes/aparelho-jantar-dourado.webp"},
    {"id": "aparelho-jantar-relevo", "categoria": "mesa", "nome": "Aparelho de jantar branco com relevo", "valor": 1049.9, "foto": "images/presentes/aparelho-jantar-relevo.webp"},
    {"id": "aparelho-jantar-perolado", "categoria": "mesa", "nome": "Aparelho de jantar com borda perolada", "valor": 1159.9, "foto": "images/presentes/aparelho-jantar-perolado.webp"},
    {"id": "faqueiro-101", "categoria": "mesa", "nome": "Faqueiro 101 peças", "valor": 1251.1, "foto": "images/presentes/faqueiro-101.webp"},
    {"id": "colher-de-pau", "categoria": "cozinha", "nome": "Colher de pau", "valor": 27.93, "foto": "images/presentes/colher-de-pau.webp"},
    {"id": "pano-de-prato", "categoria": "cozinha", "nome": "Pano de prato", "valor": 29.99, "foto": "images/presentes/pano-de-prato.webp"},
    {"id": "coz-garrafas-geladeira", "categoria": "cozinha", "nome": "Garrafa de vidro com tampa de bambu", "valor": 36, "foto": "images/presentes/coz-garrafas-geladeira.webp"},
    {"id": "coz-espremedor-alho", "categoria": "cozinha", "nome": "Espremedor de alho em inox", "valor": 39.9, "foto": "images/presentes/coz-espremedor-alho.webp"},
    {"id": "coz-descascador", "categoria": "cozinha", "nome": "Descascador de legumes com zester", "valor": 40.9, "foto": "images/presentes/coz-descascador.webp"},
    {"id": "coz-rolo-massa", "categoria": "cozinha", "nome": "Rolo de massa de silicone e bambu", "valor": 42, "foto": "images/presentes/coz-rolo-massa.webp"},
    {"id": "coz-abridor", "categoria": "cozinha", "nome": "Abridor de latas", "valor": 45.9, "foto": "images/presentes/coz-abridor.webp"},
    {"id": "coz-medidores", "categoria": "cozinha", "nome": "Jogo de colheres medidoras de bambu", "valor": 45.9, "foto": "images/presentes/coz-medidores.webp"},
    {"id": "coz-peneiras", "categoria": "cozinha", "nome": "Peneira de inox com cabo", "valor": 49.9, "foto": "images/presentes/coz-peneiras.webp"},
    {"id": "coz-tesoura", "categoria": "cozinha", "nome": "Tesoura de cozinha multiuso", "valor": 49.9, "foto": "images/presentes/coz-tesoura.webp"},
    {"id": "coz-forma-muffin", "categoria": "cozinha", "nome": "Forma de silicone para 6 cupcakes", "valor": 52.9, "foto": "images/presentes/coz-forma-muffin.webp"},
    {"id": "coz-luvas-termicas", "categoria": "cozinha", "nome": "Luva térmica para forno", "valor": 52.9, "foto": "images/presentes/coz-luvas-termicas.webp"},
    {"id": "coz-martelo-carne", "categoria": "cozinha", "nome": "Martelo para carne", "valor": 55.9, "foto": "images/presentes/coz-martelo-carne.webp"},
    {"id": "coz-coador-cafe", "categoria": "cozinha", "nome": "Coador de café de vidro com base de bambu", "valor": 55.93, "foto": "images/presentes/coz-coador-cafe.webp"},
    {"id": "forma-pudim", "categoria": "cozinha", "nome": "Forma de pudim", "valor": 57.45, "foto": "images/presentes/forma-pudim.webp"},
    {"id": "coz-escorredor-massas", "categoria": "cozinha", "nome": "Escorredor de massas em inox", "valor": 59.9, "foto": "images/presentes/coz-escorredor-massas.webp"},
    {"id": "coz-organizador-talheres", "categoria": "cozinha", "nome": "Organizador de talheres de bambu", "valor": 59.9, "foto": "images/presentes/coz-organizador-talheres.webp"},
    {"id": "coz-porta-detergente", "categoria": "cozinha", "nome": "Porta-detergente e esponja", "valor": 67.9, "foto": "images/presentes/coz-porta-detergente.webp"},
    {"id": "coz-forma-bolo", "categoria": "cozinha", "nome": "Forma de bolo inglês", "valor": 69.9, "foto": "images/presentes/coz-forma-bolo.webp"},
    {"id": "coz-afiador", "categoria": "cozinha", "nome": "Afiador de facas", "valor": 69.9, "foto": "images/presentes/coz-afiador.webp"},
    {"id": "coz-fervedor", "categoria": "cozinha", "nome": "Fervedor antiaderente 15 cm", "valor": 69.99, "foto": "images/presentes/coz-fervedor.webp"},
    {"id": "coz-formas-pizza", "categoria": "cozinha", "nome": "Forma de pizza antiaderente 35 cm", "valor": 71.99, "foto": "images/presentes/coz-formas-pizza.webp"},
    {"id": "coz-porta-papel-toalha", "categoria": "cozinha", "nome": "Porta-papel toalha de acácia", "valor": 75.9, "foto": "images/presentes/coz-porta-papel-toalha.webp"},
    {"id": "coz-tapioqueira", "categoria": "cozinha", "nome": "Tapioqueira antiaderente 24 cm", "valor": 79.9, "foto": "images/presentes/coz-tapioqueira.webp"},
    {"id": "coz-ramequins", "categoria": "cozinha", "nome": "Jogo de 6 ramequins de porcelana", "valor": 81.9, "foto": "images/presentes/coz-ramequins.webp"},
    {"id": "coz-termometro", "categoria": "cozinha", "nome": "Termômetro culinário para carne", "valor": 89.01, "foto": "images/presentes/coz-termometro.webp"},
    {"id": "potes-hermeticos", "categoria": "cozinha", "nome": "Potes herméticos", "valor": 89.9, "foto": "images/presentes/potes-hermeticos.webp"},
    {"id": "coz-aventais", "categoria": "cozinha", "nome": "Avental de cozinha estampado", "valor": 95.9, "foto": "images/presentes/coz-aventais.webp"},
    {"id": "coz-tabuas-corte", "categoria": "cozinha", "nome": "Tábua de corte", "valor": 99.9, "foto": "images/presentes/coz-tabuas-corte.webp"},
    {"id": "coz-tigelas-inox", "categoria": "cozinha", "nome": "Jogo de 3 tigelas de inox com tampa", "valor": 99.9, "foto": "images/presentes/coz-tigelas-inox.webp"},
    {"id": "coz-balanca", "categoria": "cozinha", "nome": "Balança digital de cozinha", "valor": 99.99, "foto": "images/presentes/coz-balanca.webp"},
    {"id": "coz-cuscuzeira", "categoria": "cozinha", "nome": "Cuscuzeira individual de inox", "valor": 99.99, "foto": "images/presentes/coz-cuscuzeira.webp"},
    {"id": "coz-acessorios-air-fryer", "categoria": "cozinha", "nome": "Kit de acessórios para air fryer", "valor": 109.99, "foto": "images/presentes/coz-acessorios-air-fryer.webp"},
    {"id": "utensilios-cozinha", "categoria": "cozinha", "nome": "Kit de utensílios de madeira e silicone", "valor": 118.93, "foto": "images/presentes/utensilios-cozinha.webp"},
    {"id": "assadeiras-vidro", "categoria": "cozinha", "nome": "Assadeiras de vidro Marinex (4 peças)", "valor": 124.8, "foto": "images/presentes/assadeiras-vidro.webp"},
    {"id": "porta-condimentos", "categoria": "cozinha", "nome": "Porta-condimentos com suporte", "valor": 129.9, "foto": "images/presentes/porta-condimentos.webp"},
    {"id": "garrafa-termica", "categoria": "cozinha", "nome": "Garrafa térmica", "valor": 129.9, "foto": "images/presentes/garrafa-termica.webp"},
    {"id": "coz-panela-barro", "categoria": "cozinha", "nome": "Panela de cerâmica artesanal", "valor": 129.9, "foto": "images/presentes/coz-panela-barro.webp"},
    {"id": "coz-bistequeira", "categoria": "cozinha", "nome": "Bistequeira redonda 30 cm", "valor": 139.99, "foto": "images/presentes/coz-bistequeira.webp"},
    {"id": "frigideira", "categoria": "cozinha", "nome": "Frigideira antiaderente", "valor": 149.9, "foto": "images/presentes/frigideira.webp"},
    {"id": "coz-cafeteira-italiana", "categoria": "cozinha", "nome": "Cafeteira italiana 300 ml", "valor": 169.9, "foto": "images/presentes/coz-cafeteira-italiana.webp"},
    {"id": "escorredor", "categoria": "cozinha", "nome": "Escorredor de louça", "valor": 179.9, "foto": "images/presentes/escorredor.webp"},
    {"id": "lixeira-pedal", "categoria": "cozinha", "nome": "Lixeira com pedal", "valor": 179.9, "foto": "images/presentes/lixeira-pedal.webp"},
    {"id": "coz-espagueteira", "categoria": "cozinha", "nome": "Espagueteira antiaderente 5,7 L", "valor": 219.99, "foto": "images/presentes/coz-espagueteira.webp"},
    {"id": "panela-pressao", "categoria": "cozinha", "nome": "Panela de pressão", "valor": 229.99, "foto": "images/presentes/panela-pressao.webp"},
    {"id": "wok", "categoria": "cozinha", "nome": "Wok", "valor": 259.9, "foto": "images/presentes/wok.webp"},
    {"id": "facas-cepo", "categoria": "cozinha", "nome": "Jogo de facas com cepo", "valor": 389.99, "foto": "images/presentes/facas-cepo.webp"},
    {"id": "coz-panela-ferro", "categoria": "cozinha", "nome": "Caçarola de ferro fundido esmaltada", "valor": 529.9, "foto": "images/presentes/coz-panela-ferro.webp"},
    {"id": "travessas-lasanha", "categoria": "cozinha", "nome": "Travessas refratárias Oxford para lasanha", "valor": 549.7, "foto": "images/presentes/travessas-lasanha.webp"},
    {"id": "panelas-tramontina", "categoria": "cozinha", "nome": "Jogo de panelas Tramontina Solar (6 peças)", "valor": 949, "foto": "images/presentes/panelas-tramontina.webp"},
    {"id": "chu-copos-acrilico", "categoria": "churrasco", "nome": "Jogo de 4 copos coloridos para área externa", "valor": 69.9, "foto": "images/presentes/chu-copos-acrilico.webp"},
    {"id": "chu-espetos", "categoria": "churrasco", "nome": "Kit de espetos de aço (3 peças)", "valor": 83, "foto": "images/presentes/chu-espetos.webp"},
    {"id": "chu-garfo-pegador", "categoria": "churrasco", "nome": "Kit de utensílios para churrasco (4 peças)", "valor": 101, "foto": "images/presentes/chu-garfo-pegador.webp"},
    {"id": "chu-grelha", "categoria": "churrasco", "nome": "Grelha para churrasco", "valor": 115, "foto": "images/presentes/chu-grelha.webp"},
    {"id": "chu-cooler", "categoria": "churrasco", "nome": "Caixa térmica 34 litros", "valor": 158, "foto": "images/presentes/chu-cooler.webp"},
    {"id": "chu-suqueira", "categoria": "churrasco", "nome": "Suqueira com torneira", "valor": 180, "foto": "images/presentes/chu-suqueira.webp"},
    {"id": "facas-churrasco", "categoria": "churrasco", "nome": "Jogo de facas de churrasco", "valor": 189.9, "foto": "images/presentes/facas-churrasco.webp"},
    {"id": "chu-mesa-dobravel", "categoria": "churrasco", "nome": "Mesa dobrável para área externa", "valor": 256, "foto": "images/presentes/chu-mesa-dobravel.webp"},
    {"id": "chu-churrasqueira-carvao", "categoria": "churrasco", "nome": "Churrasqueira a carvão portátil", "valor": 263, "foto": "images/presentes/chu-churrasqueira-carvao.webp"},
    {"id": "chu-cadeiras-dobraveis", "categoria": "churrasco", "nome": "Cadeira dobrável de madeira", "valor": 349.9, "foto": "images/presentes/chu-cadeiras-dobraveis.webp"},
    {"id": "chu-churrasqueira-eletrica", "categoria": "churrasco", "nome": "Churrasqueira elétrica (127 V)", "valor": 409.9, "foto": "images/presentes/chu-churrasqueira-eletrica.webp"},
    {"id": "chu-maquina-gelo", "categoria": "churrasco", "nome": "Máquina de gelo (127 V)", "valor": 983.9, "foto": "images/presentes/chu-maquina-gelo.webp"},
    {"id": "cafeteira", "categoria": "eletros", "nome": "Cafeteira Cadence Single Colors vermelha (110 V)", "valor": 109.9, "foto": "images/presentes/cafeteira.webp"},
    {"id": "ele-espremedor", "categoria": "eletros", "nome": "Espremedor de frutas (127 V)", "valor": 109.9, "foto": "images/presentes/ele-espremedor.webp"},
    {"id": "ele-moedor-cafe", "categoria": "eletros", "nome": "Moedor de café elétrico (127 V)", "valor": 124.9, "foto": "images/presentes/ele-moedor-cafe.webp"},
    {"id": "ele-aquecedor", "categoria": "eletros", "nome": "Aquecedor de ambiente (127 V)", "valor": 129.9, "foto": "images/presentes/ele-aquecedor.webp"},
    {"id": "torradeira", "categoria": "eletros", "nome": "Torradeira Ford 2 fatias inox", "valor": 139.9, "foto": "images/presentes/torradeira.webp"},
    {"id": "chaleira-eletrica", "categoria": "eletros", "nome": "Chaleira elétrica", "valor": 144.9, "foto": "images/presentes/chaleira-eletrica.webp"},
    {"id": "liquidificador", "categoria": "eletros", "nome": "Liquidificador", "valor": 149.9, "foto": "images/presentes/liquidificador.webp"},
    {"id": "ferro-vapor", "categoria": "eletros", "nome": "Ferro de passar a vapor", "valor": 149.9, "foto": "images/presentes/ferro-vapor.webp"},
    {"id": "batedeira", "categoria": "eletros", "nome": "Batedeira Philco 4 velocidades", "valor": 151.9, "foto": "images/presentes/batedeira.webp"},
    {"id": "sanduicheira", "categoria": "eletros", "nome": "Sanduicheira e grill", "valor": 152.9, "foto": "images/presentes/sanduicheira.webp"},
    {"id": "ele-waffle", "categoria": "eletros", "nome": "Máquina de waffle (127 V)", "valor": 159.9, "foto": "images/presentes/ele-waffle.webp"},
    {"id": "ele-pipoqueira", "categoria": "eletros", "nome": "Pipoqueira elétrica (127 V)", "valor": 179.9, "foto": "images/presentes/ele-pipoqueira.webp"},
    {"id": "ele-umidificador", "categoria": "eletros", "nome": "Umidificador de ar 4,8 L", "valor": 179.9, "foto": "images/presentes/ele-umidificador.webp"},
    {"id": "ele-centrifuga", "categoria": "eletros", "nome": "Centrífuga de sucos", "valor": 229.9, "foto": "images/presentes/ele-centrifuga.webp"},
    {"id": "ele-seladora", "categoria": "eletros", "nome": "Seladora a vácuo (127 V)", "valor": 229.9, "foto": "images/presentes/ele-seladora.webp"},
    {"id": "mixer", "categoria": "eletros", "nome": "Mixer 3 em 1", "valor": 234.9, "foto": "images/presentes/mixer.webp"},
    {"id": "panela-arroz", "categoria": "eletros", "nome": "Panela elétrica de arroz", "valor": 239.9, "foto": "images/presentes/panela-arroz.webp"},
    {"id": "ele-ventilador", "categoria": "eletros", "nome": "Ventilador de coluna (127 V)", "valor": 252.9, "foto": "images/presentes/ele-ventilador.webp"},
    {"id": "ele-crepeira", "categoria": "eletros", "nome": "Crepeira elétrica (127 V)", "valor": 256.9, "foto": "images/presentes/ele-crepeira.webp"},
    {"id": "ele-processador", "categoria": "eletros", "nome": "Processador de alimentos (127 V)", "valor": 263.9, "foto": "images/presentes/ele-processador.webp"},
    {"id": "ele-espumador", "categoria": "eletros", "nome": "Espumador de leite (127 V)", "valor": 269.9, "foto": "images/presentes/ele-espumador.webp"},
    {"id": "air-fryer", "categoria": "eletros", "nome": "Fritadeira air fryer", "valor": 299.9, "foto": "images/presentes/air-fryer.webp"},
    {"id": "ele-lavadora-pressao", "categoria": "eletros", "nome": "Lavadora de alta pressão (127 V)", "valor": 369.9, "foto": "images/presentes/ele-lavadora-pressao.webp"},
    {"id": "aspirador-vertical", "categoria": "eletros", "nome": "Aspirador de pó vertical", "valor": 409.9, "foto": "images/presentes/aspirador-vertical.webp"},
    {"id": "ele-maquina-pao", "categoria": "eletros", "nome": "Máquina de pão (127 V)", "valor": 549.9, "foto": "images/presentes/ele-maquina-pao.webp"},
    {"id": "purificador", "categoria": "eletros", "nome": "Purificador de água Electrolux com painel touch", "valor": 549.9, "foto": "images/presentes/purificador.webp"},
    {"id": "ele-cooktop", "categoria": "eletros", "nome": "Cooktop por indução 2 bocas (127 V)", "valor": 549.99, "foto": "images/presentes/ele-cooktop.webp"},
    {"id": "micro-ondas", "categoria": "eletros", "nome": "Micro-ondas Philco 25 litros", "valor": 599.9, "foto": "images/presentes/micro-ondas.webp"},
    {"id": "cafeteira-expresso", "categoria": "eletros", "nome": "Cafeteira expresso", "valor": 699.9, "foto": "images/presentes/cafeteira-expresso.webp"},
    {"id": "ele-coifa", "categoria": "eletros", "nome": "Depurador de ar para fogão (127 V)", "valor": 699.9, "foto": "images/presentes/ele-coifa.webp"},
    {"id": "ele-moedor-carne", "categoria": "eletros", "nome": "Moedor de carne elétrico (127 V)", "valor": 699.9, "foto": "images/presentes/ele-moedor-carne.webp"},
    {"id": "ele-maquina-costura", "categoria": "eletros", "nome": "Máquina de costura (127 V)", "valor": 969, "foto": "images/presentes/ele-maquina-costura.webp"},
    {"id": "ele-frigobar", "categoria": "eletros", "nome": "Frigobar 95 litros", "valor": 1129, "foto": "images/presentes/ele-frigobar.webp"},
    {"id": "robo-aspirador", "categoria": "eletros", "nome": "Robô aspirador", "valor": 1249.9, "foto": "images/presentes/robo-aspirador.webp"},
    {"id": "ele-fogao", "categoria": "eletros", "nome": "Fogão 4 bocas", "valor": 1499, "foto": "images/presentes/ele-fogao.webp"},
    {"id": "forno-eletrico", "categoria": "eletros", "nome": "Forno elétrico", "valor": 1859, "foto": "images/presentes/forno-eletrico.webp"},
    {"id": "lavadora", "categoria": "eletros", "nome": "Lavadora de roupas Brastemp Ative! 11 kg", "valor": 2104.99, "foto": "images/presentes/lavadora.webp"},
    {"id": "ele-freezer", "categoria": "eletros", "nome": "Freezer horizontal 307 litros (127 V)", "valor": 2229.99, "foto": "images/presentes/ele-freezer.webp"},
    {"id": "ar-condicionado", "categoria": "eletros", "nome": "Ar-condicionado split LG Inverter 11.500 BTUs quente/frio", "valor": 2574.39, "foto": "images/presentes/ar-condicionado.webp"},
    {"id": "geladeira", "categoria": "eletros", "nome": "Geladeira", "valor": 3442.99, "foto": "images/presentes/geladeira.webp"},
    {"id": "lava-loucas", "categoria": "eletros", "nome": "Lava-louças de piso", "valor": 3599, "foto": "images/presentes/lava-loucas.webp"},
    {"id": "lava-e-seca", "categoria": "eletros", "nome": "Lava e seca Brastemp", "valor": 4133, "foto": "images/presentes/lava-e-seca.webp"},
    {"id": "tec-lampadas-smart", "categoria": "tecnologia", "nome": "Kit com 3 lâmpadas inteligentes", "valor": 134.7, "foto": "images/presentes/tec-lampadas-smart.webp"},
    {"id": "tec-rede", "categoria": "tecnologia", "nome": "Rede de descanso", "valor": 199.9, "foto": "images/presentes/tec-rede.webp"},
    {"id": "tec-fones", "categoria": "tecnologia", "nome": "Fones de ouvido sem fio", "valor": 249, "foto": "images/presentes/tec-fones.webp"},
    {"id": "tec-camera-wifi", "categoria": "tecnologia", "nome": "Câmera de segurança Wi-Fi 360°", "valor": 269.9, "foto": "images/presentes/tec-camera-wifi.webp"},
    {"id": "tec-binoculos", "categoria": "tecnologia", "nome": "Binóculos para trilhas e passeios", "valor": 300, "foto": "images/presentes/tec-binoculos.webp"},
    {"id": "tec-caixa-som", "categoria": "tecnologia", "nome": "Caixa de som bluetooth", "valor": 339.9, "foto": "images/presentes/tec-caixa-som.webp"},
    {"id": "tec-cadeiras-praia", "categoria": "tecnologia", "nome": "Cadeiras de praia com guarda-sol", "valor": 350, "foto": "images/presentes/tec-cadeiras-praia.webp"},
    {"id": "tec-streaming", "categoria": "tecnologia", "nome": "Aparelho de streaming para a TV", "valor": 362.9, "foto": "images/presentes/tec-streaming.webp"},
    {"id": "tec-barraca", "categoria": "tecnologia", "nome": "Barraca de camping para dois", "valor": 400, "foto": "images/presentes/tec-barraca.webp"},
    {"id": "tec-relogio-inteligente", "categoria": "tecnologia", "nome": "Relógio inteligente com GPS", "valor": 449, "foto": "images/presentes/tec-relogio-inteligente.webp"},
    {"id": "tec-violao", "categoria": "tecnologia", "nome": "Violão", "valor": 500, "foto": "images/presentes/tec-violao.webp"},
    {"id": "tec-fechadura-digital", "categoria": "tecnologia", "nome": "Fechadura digital com maçaneta", "valor": 599.9, "foto": "images/presentes/tec-fechadura-digital.webp"},
    {"id": "tec-camera-instantanea", "categoria": "tecnologia", "nome": "Câmera instantânea", "valor": 600, "foto": "images/presentes/tec-camera-instantanea.webp"},
    {"id": "tec-impressora", "categoria": "tecnologia", "nome": "Impressora multifuncional", "valor": 700, "foto": "images/presentes/tec-impressora.webp"},
    {"id": "tec-leitor-digital", "categoria": "tecnologia", "nome": "Leitor de livros digitais", "valor": 700, "foto": "images/presentes/tec-leitor-digital.webp"},
    {"id": "tec-assistente-voz", "categoria": "tecnologia", "nome": "Caixa de som com assistente de voz", "valor": 791.9, "foto": "images/presentes/tec-assistente-voz.webp"},
    {"id": "tec-bicicleta", "categoria": "tecnologia", "nome": "Bicicleta", "valor": 1200, "foto": "images/presentes/tec-bicicleta.webp"},
    {"id": "tec-tablet", "categoria": "tecnologia", "nome": "Tablet de 10 polegadas", "valor": 1299, "foto": "images/presentes/tec-tablet.webp"},
    {"id": "tec-projetor", "categoria": "tecnologia", "nome": "Projetor Full HD", "valor": 1449.9, "foto": "images/presentes/tec-projetor.webp"},
    {"id": "smart-tv", "categoria": "tecnologia", "nome": "Smart TV Samsung 42 polegadas", "valor": 1893.68, "foto": "images/presentes/smart-tv.webp"},
    {"id": "tec-videogame", "categoria": "tecnologia", "nome": "Videogame", "valor": 3500, "foto": "images/presentes/tec-videogame.webp"},
    {"id": "sala-porta-retratos", "categoria": "sala", "nome": "Par de porta-retratos", "valor": 65.9, "foto": "images/presentes/sala-porta-retratos.webp"},
    {"id": "sala-cachepos", "categoria": "sala", "nome": "Cachepô de cerâmica 18 cm", "valor": 129.9, "foto": "images/presentes/sala-cachepos.webp"},
    {"id": "sala-almofadas", "categoria": "sala", "nome": "Almofada listrada 60 cm", "valor": 139.9, "foto": "images/presentes/sala-almofadas.webp"},
    {"id": "sala-manta-sofa", "categoria": "sala", "nome": "Manta para o sofá", "valor": 139.9, "foto": "images/presentes/sala-manta-sofa.webp"},
    {"id": "sala-relogio-parede", "categoria": "sala", "nome": "Relógio de parede", "valor": 149.9, "foto": "images/presentes/sala-relogio-parede.webp"},
    {"id": "sala-nichos", "categoria": "sala", "nome": "Conjunto de 3 nichos de parede", "valor": 159.9, "foto": "images/presentes/sala-nichos.webp"},
    {"id": "sala-puff", "categoria": "sala", "nome": "Puff redondo", "valor": 199.9, "foto": "images/presentes/sala-puff.webp"},
    {"id": "sala-cortina", "categoria": "sala", "nome": "Cortina para a sala (2 peças)", "valor": 239.9, "foto": "images/presentes/sala-cortina.webp"},
    {"id": "sala-quadros", "categoria": "sala", "nome": "Quadro decorativo 50 x 70 cm", "valor": 269.9, "foto": "images/presentes/sala-quadros.webp"},
    {"id": "sala-pendente", "categoria": "sala", "nome": "Pendente para a sala de jantar", "valor": 309.9, "foto": "images/presentes/sala-pendente.webp"},
    {"id": "sala-cadeiras", "categoria": "sala", "nome": "Par de cadeiras de jantar", "valor": 359.8, "foto": "images/presentes/sala-cadeiras.webp"},
    {"id": "sala-espelho", "categoria": "sala", "nome": "Espelho decorativo 37 x 100 cm", "valor": 379.9, "foto": "images/presentes/sala-espelho.webp"},
    {"id": "sala-luminaria-piso", "categoria": "sala", "nome": "Luminária de chão", "valor": 399.9, "foto": "images/presentes/sala-luminaria-piso.webp"},
    {"id": "tapete-sala", "categoria": "sala", "nome": "Tapete para a sala", "valor": 479.9, "foto": "images/presentes/tapete-sala.webp"},
    {"id": "sala-estante", "categoria": "sala", "nome": "Estante para livros", "valor": 499.9, "foto": "images/presentes/sala-estante.webp"},
    {"id": "sala-mesa-centro", "categoria": "sala", "nome": "Mesa de centro redonda", "valor": 499.9, "foto": "images/presentes/sala-mesa-centro.webp"},
    {"id": "cota-sofa", "categoria": "sala", "nome": "Cota para o sofá novo", "valor": 500, "foto": "images/presentes/cota-sofa.webp"},
    {"id": "sala-cota-mesa-jantar", "categoria": "sala", "nome": "Cota para a mesa de jantar", "valor": 500, "foto": "images/presentes/sala-cota-mesa-jantar.webp"},
    {"id": "sala-rack-tv", "categoria": "sala", "nome": "Rack para a TV", "valor": 779.9, "foto": "images/presentes/sala-rack-tv.webp"},
    {"id": "sala-aparador", "categoria": "sala", "nome": "Aparador", "valor": 799.9, "foto": "images/presentes/sala-aparador.webp"},
    {"id": "cristaleira", "categoria": "sala", "nome": "Cristaleira", "valor": 934.62, "foto": "images/presentes/cristaleira.webp"},
    {"id": "sala-poltrona", "categoria": "sala", "nome": "Poltrona", "valor": 979.9, "foto": "images/presentes/sala-poltrona.webp"},
    {"id": "qto-organizador-maquiagem", "categoria": "quarto", "nome": "Organizador giratório de maquiagem", "valor": 49.99, "foto": "images/presentes/qto-organizador-maquiagem.webp"},
    {"id": "qto-tapete-banheiro", "categoria": "quarto", "nome": "Toalha de piso para banheiro", "valor": 67.9, "foto": "images/presentes/qto-tapete-banheiro.webp"},
    {"id": "qto-escova-dentes", "categoria": "quarto", "nome": "Escova de dentes elétrica", "valor": 69.9, "foto": "images/presentes/qto-escova-dentes.webp"},
    {"id": "qto-toalhas-lavabo", "categoria": "quarto", "nome": "Par de toalhas de lavabo", "valor": 83.99, "foto": "images/presentes/qto-toalhas-lavabo.webp"},
    {"id": "qto-velas", "categoria": "quarto", "nome": "Vela aromática", "valor": 87.9, "foto": "images/presentes/qto-velas.webp"},
    {"id": "qto-pantufas", "categoria": "quarto", "nome": "Par de pantufas", "valor": 89.9, "foto": "images/presentes/qto-pantufas.webp"},
    {"id": "qto-difusor", "categoria": "quarto", "nome": "Difusor de aromas", "valor": 99.9, "foto": "images/presentes/qto-difusor.webp"},
    {"id": "qto-balanca-corporal", "categoria": "quarto", "nome": "Balança corporal digital", "valor": 109.9, "foto": "images/presentes/qto-balanca-corporal.webp"},
    {"id": "qto-porta-joias", "categoria": "quarto", "nome": "Porta-joias", "valor": 159.9, "foto": "images/presentes/qto-porta-joias.webp"},
    {"id": "travesseiros", "categoria": "quarto", "nome": "Par de travesseiros", "valor": 179.8, "foto": "images/presentes/travesseiros.webp"},
    {"id": "qto-barbeador", "categoria": "quarto", "nome": "Barbeador elétrico", "valor": 179.9, "foto": "images/presentes/qto-barbeador.webp"},
    {"id": "qto-prancha", "categoria": "quarto", "nome": "Prancha alisadora", "valor": 183.9, "foto": "images/presentes/qto-prancha.webp"},
    {"id": "abajur", "categoria": "quarto", "nome": "Abajur para o quarto", "valor": 199.9, "foto": "images/presentes/abajur.webp"},
    {"id": "qto-secador-cabelo", "categoria": "quarto", "nome": "Secador de cabelo", "valor": 199.9, "foto": "images/presentes/qto-secador-cabelo.webp"},
    {"id": "qto-massageador", "categoria": "quarto", "nome": "Hidromassageador para os pés (127 V)", "valor": 199.9, "foto": "images/presentes/qto-massageador.webp"},
    {"id": "qto-protetor-colchao", "categoria": "quarto", "nome": "Protetor de colchão queen", "valor": 199.99, "foto": "images/presentes/qto-protetor-colchao.webp"},
    {"id": "qto-peseira", "categoria": "quarto", "nome": "Peseira para a cama", "valor": 216.93, "foto": "images/presentes/qto-peseira.webp"},
    {"id": "roupoes", "categoria": "quarto", "nome": "Par de roupões", "valor": 258, "foto": "images/presentes/roupoes.webp"},
    {"id": "qto-escova-secadora", "categoria": "quarto", "nome": "Escova secadora", "valor": 259.9, "foto": "images/presentes/qto-escova-secadora.webp"},
    {"id": "edredom-queen", "categoria": "quarto", "nome": "Edredom queen", "valor": 299, "foto": "images/presentes/edredom-queen.webp"},
    {"id": "lencol-queen", "categoria": "quarto", "nome": "Jogo de lençol queen", "valor": 299, "foto": "images/presentes/lencol-queen.webp"},
    {"id": "qto-mesa-cabeceira", "categoria": "quarto", "nome": "Mesa de cabeceira", "valor": 299.9, "foto": "images/presentes/qto-mesa-cabeceira.webp"},
    {"id": "kit-banheiro", "categoria": "quarto", "nome": "Conjunto de acessórios para banheiro", "valor": 330.5, "foto": "images/presentes/kit-banheiro.webp"},
    {"id": "jogo-de-banho", "categoria": "quarto", "nome": "Jogo de banho gigante", "valor": 344.99, "foto": "images/presentes/jogo-de-banho.webp"},
    {"id": "cota-cama", "categoria": "quarto", "nome": "Cota para a cama nova", "valor": 500, "foto": "images/presentes/cota-cama.webp"},
    {"id": "casa-capacho", "categoria": "casa", "nome": "Capacho para a porta", "valor": 69.9, "foto": "images/presentes/casa-capacho.webp"},
    {"id": "mesa-multiuso", "categoria": "casa", "nome": "Mesa multiuso Tramontina preta", "valor": 69.9, "foto": "images/presentes/mesa-multiuso.webp"},
    {"id": "porta-chaves", "categoria": "casa", "nome": "Porta-chaves", "valor": 72.9, "foto": "images/presentes/porta-chaves.webp"},
    {"id": "cabides-flocados", "categoria": "casa", "nome": "Kit de cabides flocados", "valor": 119.7, "foto": "images/presentes/cabides-flocados.webp"},
    {"id": "casa-caixas-organizadoras", "categoria": "casa", "nome": "Caixa organizadora com tampa", "valor": 119.9, "foto": "images/presentes/casa-caixas-organizadoras.webp"},
    {"id": "casa-varal", "categoria": "casa", "nome": "Varal de chão", "valor": 151, "foto": "images/presentes/casa-varal.webp"},
    {"id": "casa-tabua-passar", "categoria": "casa", "nome": "Tábua de passar roupa", "valor": 157, "foto": "images/presentes/casa-tabua-passar.webp"},
    {"id": "casa-kit-limpeza", "categoria": "casa", "nome": "Kit mop giratório com balde", "valor": 159.9, "foto": "images/presentes/casa-kit-limpeza.webp"},
    {"id": "cesto-de-roupa", "categoria": "casa", "nome": "Cesto de roupa", "valor": 179.9, "foto": "images/presentes/cesto-de-roupa.webp"},
    {"id": "casa-escada", "categoria": "casa", "nome": "Escada doméstica de 3 degraus", "valor": 189, "foto": "images/presentes/casa-escada.webp"},
    {"id": "casa-ferramentas", "categoria": "casa", "nome": "Kit de ferramentas com maleta", "valor": 189.9, "foto": "images/presentes/casa-ferramentas.webp"},
    {"id": "casa-sapateira", "categoria": "casa", "nome": "Sapateira com porta basculante", "valor": 219.9, "foto": "images/presentes/casa-sapateira.webp"},
    {"id": "casa-parafusadeira", "categoria": "casa", "nome": "Parafusadeira e furadeira a bateria", "valor": 229.9, "foto": "images/presentes/casa-parafusadeira.webp"},
    {"id": "casa-banquetas", "categoria": "casa", "nome": "Banqueta alta", "valor": 289.9, "foto": "images/presentes/casa-banquetas.webp"},
    {"id": "casa-cabideiro", "categoria": "casa", "nome": "Cabideiro de pé", "valor": 299.9, "foto": "images/presentes/casa-cabideiro.webp"},
    {"id": "rotuladora", "categoria": "casa", "nome": "Rotuladora eletrônica Brother PT-80", "valor": 329, "foto": "images/presentes/rotuladora.webp"},
    {"id": "casa-escrivaninha", "categoria": "casa", "nome": "Escrivaninha", "valor": 599.9, "foto": "images/presentes/casa-escrivaninha.webp"},
    {"id": "div-pasta-dente", "categoria": "divertidos", "nome": "A pasta de dente apertada do jeito certo", "valor": 30, "foto": "images/presentes/div-pasta-dente.webp"},
    {"id": "div-ronco", "categoria": "divertidos", "nome": "Protetores de ouvido contra o ronco", "valor": 40, "foto": "images/presentes/div-ronco.webp"},
    {"id": "div-acai", "categoria": "divertidos", "nome": "O açaí de depois da academia", "valor": 45, "foto": "images/presentes/div-acai.webp"},
    {"id": "div-dormir-ate-tarde", "categoria": "divertidos", "nome": "Dormir até meio-dia depois da festa", "valor": 50, "foto": "images/presentes/div-dormir-ate-tarde.webp"},
    {"id": "div-brigadeiro", "categoria": "divertidos", "nome": "Brigadeiro de panela para as noites de frio", "valor": 50, "foto": "images/presentes/div-brigadeiro.webp"},
    {"id": "div-raquete-mosquito", "categoria": "divertidos", "nome": "O mata-mosquito das noites de verão", "valor": 50, "foto": "images/presentes/div-raquete-mosquito.webp"},
    {"id": "div-pastel-feira", "categoria": "divertidos", "nome": "Pastel e caldo de cana na feira", "valor": 60, "foto": "images/presentes/div-pastel-feira.webp"},
    {"id": "div-pipoca-filme", "categoria": "divertidos", "nome": "Pipoca e filme no primeiro domingo", "valor": 60, "foto": "images/presentes/div-pipoca-filme.webp"},
    {"id": "div-tampa-vaso", "categoria": "divertidos", "nome": "Para a eterna discussão da tampa do vaso", "valor": 60, "foto": "images/presentes/div-tampa-vaso.webp"},
    {"id": "div-sorvete-sexta", "categoria": "divertidos", "nome": "O pote de sorvete das sextas-feiras", "valor": 60, "foto": "images/presentes/div-sorvete-sexta.webp"},
    {"id": "div-corte-cabelo", "categoria": "divertidos", "nome": "O corte de cabelo do noivo antes do casamento", "valor": 60, "foto": "images/presentes/div-corte-cabelo.webp"},
    {"id": "div-manicure", "categoria": "divertidos", "nome": "A manicure da noiva", "valor": 60, "foto": "images/presentes/div-manicure.webp"},
    {"id": "div-guarda-chuva", "categoria": "divertidos", "nome": "O guarda-chuva esquecido no carro de aplicativo", "valor": 60, "foto": "images/presentes/div-guarda-chuva.webp"},
    {"id": "div-chinelo", "categoria": "divertidos", "nome": "Chinelos para depois da festa (adeus, salto alto)", "valor": 60, "foto": "images/presentes/div-chinelo.webp"},
    {"id": "div-carregador", "categoria": "divertidos", "nome": "O carregador de celular que sempre some", "valor": 60, "foto": "images/presentes/div-carregador.webp"},
    {"id": "div-sobremesa-domingo", "categoria": "divertidos", "nome": "A sobremesa do almoço de domingo em família", "valor": 60, "foto": "images/presentes/div-sobremesa-domingo.webp"},
    {"id": "div-chocolate-pazes", "categoria": "divertidos", "nome": "Chocolate para as pazes da primeira briga", "valor": 70, "foto": "images/presentes/div-chocolate-pazes.webp"},
    {"id": "div-planta", "categoria": "divertidos", "nome": "A primeira planta que vão esquecer de regar", "valor": 70, "foto": "images/presentes/div-planta.webp"},
    {"id": "div-padaria", "categoria": "divertidos", "nome": "O pão quentinho das manhãs de domingo", "valor": 70, "foto": "images/presentes/div-padaria.webp"},
    {"id": "div-pizza-casa-nova", "categoria": "divertidos", "nome": "A pizza da primeira noite na casa nova", "valor": 80, "foto": "images/presentes/div-pizza-casa-nova.webp"},
    {"id": "div-despertador", "categoria": "divertidos", "nome": "Um despertador para quem não acorda", "valor": 80, "foto": "images/presentes/div-despertador.webp"},
    {"id": "div-lavanderia", "categoria": "divertidos", "nome": "A lavanderia do edredom que não cabe na máquina", "valor": 80, "foto": "images/presentes/div-lavanderia.webp"},
    {"id": "div-ovo-pascoa", "categoria": "divertidos", "nome": "O primeiro ovo de Páscoa da casa", "valor": 80, "foto": "images/presentes/div-ovo-pascoa.webp"},
    {"id": "div-cafe-segundas", "categoria": "divertidos", "nome": "O café de toda segunda-feira", "valor": 90, "foto": "images/presentes/div-cafe-segundas.webp"},
    {"id": "div-controle-remoto", "categoria": "divertidos", "nome": "Um controle remoto para cada (fim das brigas)", "valor": 90, "foto": "images/presentes/div-controle-remoto.webp"},
    {"id": "div-hamburguer", "categoria": "divertidos", "nome": "O hambúrguer da preguiça de sexta", "valor": 90, "foto": "images/presentes/div-hamburguer.webp"},
    {"id": "div-quebra-cabeca", "categoria": "divertidos", "nome": "Quebra-cabeça de mil peças para testar a paciência", "valor": 90, "foto": "images/presentes/div-quebra-cabeca.webp"},
    {"id": "div-amigo-secreto", "categoria": "divertidos", "nome": "O amigo secreto de fim de ano", "valor": 100, "foto": "images/presentes/div-amigo-secreto.webp"},
    {"id": "div-chuveiro-queimado", "categoria": "divertidos", "nome": "Para o primeiro chuveiro queimado", "valor": 110, "foto": "images/presentes/div-chuveiro-queimado.webp"},
    {"id": "div-kit-ressaca", "categoria": "divertidos", "nome": "Kit para o dia seguinte da festa", "valor": 120, "foto": "images/presentes/div-kit-ressaca.webp"},
    {"id": "div-pneu-furado", "categoria": "divertidos", "nome": "O primeiro pneu furado", "valor": 120, "foto": "images/presentes/div-pneu-furado.webp"},
    {"id": "div-academia", "categoria": "divertidos", "nome": "A mensalidade da academia que ninguém vai usar", "valor": 120, "foto": "images/presentes/div-academia.webp"},
    {"id": "div-boliche", "categoria": "divertidos", "nome": "Noite de boliche", "valor": 120, "foto": "images/presentes/div-boliche.webp"},
    {"id": "div-flores-data", "categoria": "divertidos", "nome": "Flores para quando esquecerem uma data importante", "valor": 120, "foto": "images/presentes/div-flores-data.webp"},
    {"id": "div-bolo-aniversario", "categoria": "divertidos", "nome": "O bolo do primeiro aniversário de cada um", "valor": 120, "foto": "images/presentes/div-bolo-aniversario.webp"},
    {"id": "div-volta-da-festa", "categoria": "divertidos", "nome": "A volta para casa depois da festa", "valor": 130, "foto": "images/presentes/div-volta-da-festa.webp"},
    {"id": "div-botijao-gas", "categoria": "divertidos", "nome": "O botijão de gás do primeiro mês", "valor": 130, "foto": "images/presentes/div-botijao-gas.webp"},
    {"id": "div-louca", "categoria": "divertidos", "nome": "Para nunca brigarem por causa da louça", "valor": 140, "foto": "images/presentes/div-louca.webp"},
    {"id": "div-racao-pet", "categoria": "divertidos", "nome": "A ração do primeiro pet da casa", "valor": 150, "foto": "images/presentes/div-racao-pet.webp"},
    {"id": "div-chaveiro", "categoria": "divertidos", "nome": "O chaveiro de quando ficarem trancados para fora", "valor": 150, "foto": "images/presentes/div-chaveiro.webp"},
    {"id": "div-cobertor-cada", "categoria": "divertidos", "nome": "Um cobertor para cada (fim da briga pelo edredom)", "valor": 150, "foto": "images/presentes/div-cobertor-cada.webp"},
    {"id": "div-jogos-tabuleiro", "categoria": "divertidos", "nome": "Jogos de tabuleiro para as noites de chuva", "valor": 150, "foto": "images/presentes/div-jogos-tabuleiro.webp"},
    {"id": "div-karaoke", "categoria": "divertidos", "nome": "Noite de karaokê", "valor": 150, "foto": "images/presentes/div-karaoke.webp"},
    {"id": "div-presente-sogra", "categoria": "divertidos", "nome": "O presente de aniversário da sogra", "valor": 150, "foto": "images/presentes/div-presente-sogra.webp"},
    {"id": "div-wifi", "categoria": "divertidos", "nome": "O repetidor para o Wi-Fi chegar no quarto", "valor": 150, "foto": "images/presentes/div-wifi.webp"},
    {"id": "div-feijoada", "categoria": "divertidos", "nome": "A feijoada de sábado", "valor": 160, "foto": "images/presentes/div-feijoada.webp"},
    {"id": "div-stand-up", "categoria": "divertidos", "nome": "Show de stand-up comedy", "valor": 160, "foto": "images/presentes/div-stand-up.webp"},
    {"id": "div-churrasco", "categoria": "divertidos", "nome": "Churrasco de inauguração da casa", "valor": 170, "foto": "images/presentes/div-churrasco.webp"},
    {"id": "div-conta-de-luz", "categoria": "divertidos", "nome": "A conta de luz do primeiro mês", "valor": 180, "foto": "images/presentes/div-conta-de-luz.webp"},
    {"id": "div-faxina", "categoria": "divertidos", "nome": "Faxina depois da mudança", "valor": 180, "foto": "images/presentes/div-faxina.webp"},
    {"id": "div-escape-room", "categoria": "divertidos", "nome": "Desafio de escape room a dois", "valor": 180, "foto": "images/presentes/div-escape-room.webp"},
    {"id": "div-encanador", "categoria": "divertidos", "nome": "O encanador do primeiro vazamento", "valor": 180, "foto": "images/presentes/div-encanador.webp"},
    {"id": "div-aula-culinaria", "categoria": "divertidos", "nome": "Aula de culinária para os noivos", "valor": 190, "foto": "images/presentes/div-aula-culinaria.webp"},
    {"id": "div-primeira-multa", "categoria": "divertidos", "nome": "A primeira multa de trânsito do casal", "valor": 195, "foto": "images/presentes/div-primeira-multa.webp"},
    {"id": "div-sem-cozinhar", "categoria": "divertidos", "nome": "Um fim de semana sem cozinhar", "valor": 220, "foto": "images/presentes/div-sem-cozinhar.webp"},
    {"id": "div-series-filmes", "categoria": "divertidos", "nome": "Um ano de séries e filmes", "valor": 240, "foto": "images/presentes/div-series-filmes.webp"},
    {"id": "div-montar-moveis", "categoria": "divertidos", "nome": "Montar os móveis sem nenhuma briga", "valor": 250, "foto": "images/presentes/div-montar-moveis.webp"},
    {"id": "div-jantar-1-mes", "categoria": "divertidos", "nome": "O jantar de um mês de casados", "valor": 260, "foto": "images/presentes/div-jantar-1-mes.webp"},
    {"id": "div-mercado", "categoria": "divertidos", "nome": "A primeira compra de mercado", "valor": 300, "foto": "images/presentes/div-mercado.webp"},
    {"id": "div-gasolina", "categoria": "divertidos", "nome": "O tanque cheio da primeira viagem de carro", "valor": 300, "foto": "images/presentes/div-gasolina.webp"},
    {"id": "div-parque-diversoes", "categoria": "divertidos", "nome": "Um dia no parque de diversões", "valor": 300, "foto": "images/presentes/div-parque-diversoes.webp"},
    {"id": "div-reveillon", "categoria": "divertidos", "nome": "O primeiro Réveillon de casados", "valor": 300, "foto": "images/presentes/div-reveillon.webp"},
    {"id": "div-ceia-natal", "categoria": "divertidos", "nome": "A primeira ceia de Natal na casa nova", "valor": 350, "foto": "images/presentes/div-ceia-natal.webp"},
    {"id": "div-mudanca", "categoria": "divertidos", "nome": "O caminhão da mudança", "valor": 380, "foto": "images/presentes/div-mudanca.webp"},
    {"id": "div-festa-1-ano", "categoria": "divertidos", "nome": "A festa de um ano de casados", "valor": 500, "foto": "images/presentes/div-festa-1-ano.webp"},
    {"id": "div-vinho-1-ano", "categoria": "divertidos", "nome": "O vinho do primeiro aniversário", "valor": 150, "foto": "images/presentes/div-vinho-1-ano.webp", "oculto": true},
    {"id": "teste-pix", "categoria": "casa", "nome": "Teste de pagamento", "descricao": "Só aparece com ?teste=1 no endereço. Aceita apenas PIX.", "valor": 1, "oculto": true, "somentePix": true}
  ]
});
