/*
 * LISTA DE PRESENTES — edite só o que está entre as chaves.
 *
 * - valor em reais (ponto nos centavos: 89.9 = R$ 89,90)
 * - id único, só minúsculas, números e hífen; não mude o id de um presente que já recebeu pagamento
 * - foto: imagem quadrada com fundo branco (600 x 600 px) na pasta images/presentes; sem foto, aparece um ícone
 * - descricao (opcional): uma frase curta embaixo do nome
 * - "oculto": true tira da lista sem apagar; "somentePix": true bloqueia o cartão no item
 * - a ordem aqui é a ordem em que os presentes aparecem na página
 *
 * Este arquivo é lido pela página e pelo servidor (o servidor cobra sempre o valor daqui).
 */
(function (lista) {
  if (typeof module === 'object' && module.exports) module.exports = lista;
  else window.LISTA_DE_PRESENTES = lista;
})({
  "valorLivre": {
    "ativo": true,
    "minimo": 20,
    "maximo": 10000,
    "sugestoes": [50, 100, 200, 500]
  },
  "cartao": {
    "ativo": true,
    "valorMinimo": 20,
    "maxParcelas": 12
  },
  "categorias": [
    {"id": "lua-de-mel", "nome": "Lua de mel", "descricao": "Para a nossa primeira viagem como casados."},
    {"id": "mesa", "nome": "Mesa posta", "descricao": "Para receber a família e os amigos."},
    {"id": "cozinha", "nome": "Cozinha", "descricao": "Para cozinhar juntos."},
    {"id": "eletros", "nome": "Eletrodomésticos", "descricao": "Para o dia a dia da casa."},
    {"id": "casa", "nome": "Casa", "descricao": "Os detalhes que fazem um lar."},
    {"id": "divertidos", "nome": "Divertidos", "descricao": "Para rir e ajudar no começo da vida a dois."}
  ],
  "presentes": [
    {"id": "ldm-cafe-na-cama", "categoria": "lua-de-mel", "nome": "Café da manhã na cama", "valor": 150, "foto": "images/presentes/ldm-cafe-na-cama.webp"},
    {"id": "ldm-kit-praia", "categoria": "lua-de-mel", "nome": "Kit praia para a viagem", "valor": 160, "foto": "images/presentes/ldm-kit-praia.webp"},
    {"id": "ldm-drinks-por-do-sol", "categoria": "lua-de-mel", "nome": "Drinks ao pôr do sol", "valor": 180, "foto": "images/presentes/ldm-drinks-por-do-sol.webp"},
    {"id": "ldm-transfer", "categoria": "lua-de-mel", "nome": "Transfer do aeroporto ao hotel", "valor": 190, "foto": "images/presentes/ldm-transfer.webp"},
    {"id": "ldm-vinho-e-queijos", "categoria": "lua-de-mel", "nome": "Vinho e queijos no hotel", "valor": 240, "foto": "images/presentes/ldm-vinho-e-queijos.webp"},
    {"id": "ldm-carro-alugado", "categoria": "lua-de-mel", "nome": "Um dia de carro alugado", "valor": 260, "foto": "images/presentes/ldm-carro-alugado.webp"},
    {"id": "ldm-seguro-viagem", "categoria": "lua-de-mel", "nome": "Seguro viagem", "valor": 280, "foto": "images/presentes/ldm-seguro-viagem.webp"},
    {"id": "ldm-snorkel", "categoria": "lua-de-mel", "nome": "Mergulho com snorkel", "valor": 290, "foto": "images/presentes/ldm-snorkel.webp"},
    {"id": "ldm-passeio-barco", "categoria": "lua-de-mel", "nome": "Passeio de barco", "valor": 320, "foto": "images/presentes/ldm-passeio-barco.webp"},
    {"id": "ldm-jantar-romantico", "categoria": "lua-de-mel", "nome": "Jantar romântico", "valor": 350, "foto": "images/presentes/ldm-jantar-romantico.webp"},
    {"id": "ldm-massagem", "categoria": "lua-de-mel", "nome": "Massagem para dois", "valor": 380, "foto": "images/presentes/ldm-massagem.webp"},
    {"id": "ldm-show", "categoria": "lua-de-mel", "nome": "Ingressos para um show", "valor": 420, "foto": "images/presentes/ldm-show.webp"},
    {"id": "ldm-upgrade-quarto", "categoria": "lua-de-mel", "nome": "Upgrade para quarto com vista", "valor": 480, "foto": "images/presentes/ldm-upgrade-quarto.webp"},
    {"id": "ldm-dia-de-spa", "categoria": "lua-de-mel", "nome": "Dia de spa", "valor": 560, "foto": "images/presentes/ldm-dia-de-spa.webp"},
    {"id": "ldm-diaria-hotel", "categoria": "lua-de-mel", "nome": "Uma diária no hotel", "valor": 650, "foto": "images/presentes/ldm-diaria-hotel.webp"},
    {"id": "ldm-ensaio-fotos", "categoria": "lua-de-mel", "nome": "Ensaio de fotos na viagem", "valor": 800, "foto": "images/presentes/ldm-ensaio-fotos.webp"},
    {"id": "ldm-helicoptero", "categoria": "lua-de-mel", "nome": "Passeio de helicóptero", "valor": 950, "foto": "images/presentes/ldm-helicoptero.webp"},
    {"id": "ldm-passagem-noiva", "categoria": "lua-de-mel", "nome": "Passagem da noiva", "valor": 1500, "foto": "images/presentes/ldm-passagem-noiva.webp"},
    {"id": "ldm-passagem-noivo", "categoria": "lua-de-mel", "nome": "Passagem do noivo", "valor": 1500, "foto": "images/presentes/ldm-passagem-noivo.webp"},
    {"id": "ldm-tres-noites", "categoria": "lua-de-mel", "nome": "Três noites de hotel", "valor": 1950, "foto": "images/presentes/ldm-tres-noites.webp"},
    {"id": "tabua-de-frios", "categoria": "mesa", "nome": "Tábua de frios", "valor": 44.89, "foto": "images/presentes/tabua-de-frios.webp"},
    {"id": "jogo-americano", "categoria": "mesa", "nome": "Jogo americano (4 lugares)", "valor": 69.99, "foto": "images/presentes/jogo-americano.webp"},
    {"id": "conjunto-frios", "categoria": "mesa", "nome": "Conjunto para frios", "valor": 72.3, "foto": "images/presentes/conjunto-frios.webp"},
    {"id": "pratos-quadrados", "categoria": "mesa", "nome": "Jogo de pratos quadrados", "valor": 75.72, "foto": "images/presentes/pratos-quadrados.webp"},
    {"id": "jarra-vidro", "categoria": "mesa", "nome": "Jarra de vidro", "valor": 89.9, "foto": "images/presentes/jarra-vidro.webp"},
    {"id": "copos-cristal", "categoria": "mesa", "nome": "Par de copos de cristal", "valor": 99.9, "foto": "images/presentes/copos-cristal.webp"},
    {"id": "sousplats", "categoria": "mesa", "nome": "Conjunto de sousplats", "valor": 100.85, "foto": "images/presentes/sousplats.webp"},
    {"id": "talheres-pizza", "categoria": "mesa", "nome": "Kit de talheres para pizza", "valor": 123.58, "foto": "images/presentes/talheres-pizza.webp"},
    {"id": "sobremesa-viena", "categoria": "mesa", "nome": "Jogo de sobremesa Viena (vidro)", "valor": 136.26, "foto": "images/presentes/sobremesa-viena.webp"},
    {"id": "xicaras-cafe", "categoria": "mesa", "nome": "Jogo de 4 xícaras de café", "valor": 139.9, "foto": "images/presentes/xicaras-cafe.webp"},
    {"id": "toalha-mesa", "categoria": "mesa", "nome": "Toalha de mesa", "valor": 169.9, "foto": "images/presentes/toalha-mesa.webp"},
    {"id": "balde-gelo", "categoria": "mesa", "nome": "Balde de gelo inox", "valor": 179.9, "foto": "images/presentes/balde-gelo.webp"},
    {"id": "tacas-espumante", "categoria": "mesa", "nome": "Jogo de taças para espumante", "valor": 179.9, "foto": "images/presentes/tacas-espumante.webp"},
    {"id": "comida-oriental", "categoria": "mesa", "nome": "Conjunto para comida oriental", "valor": 217.35, "foto": "images/presentes/comida-oriental.webp"},
    {"id": "tacas-vinho", "categoria": "mesa", "nome": "Conjunto de taças para vinho", "valor": 234.48, "foto": "images/presentes/tacas-vinho.webp"},
    {"id": "aparelho-jantar-estampado", "categoria": "mesa", "nome": "Aparelho de jantar azul estampado", "valor": 249.33, "foto": "images/presentes/aparelho-jantar-estampado.webp"},
    {"id": "petisqueira", "categoria": "mesa", "nome": "Petisqueira giratória de bambu", "valor": 320.14, "foto": "images/presentes/petisqueira.webp"},
    {"id": "aparelho-fondue", "categoria": "mesa", "nome": "Aparelho de fondue", "valor": 461.77, "foto": "images/presentes/aparelho-fondue.webp"},
    {"id": "aparelho-jantar-relevo", "categoria": "mesa", "nome": "Aparelho de jantar branco com relevo", "valor": 477.76, "foto": "images/presentes/aparelho-jantar-relevo.webp"},
    {"id": "aparelho-jantar-perolado", "categoria": "mesa", "nome": "Aparelho de jantar com borda perolada", "valor": 477.76, "foto": "images/presentes/aparelho-jantar-perolado.webp"},
    {"id": "aparelho-jantar-azul", "categoria": "mesa", "nome": "Aparelho de jantar azul-claro", "valor": 507.45, "foto": "images/presentes/aparelho-jantar-azul.webp"},
    {"id": "faqueiro-42", "categoria": "mesa", "nome": "Faqueiro 42 peças", "valor": 598.83, "foto": "images/presentes/faqueiro-42.webp"},
    {"id": "faqueiro-101", "categoria": "mesa", "nome": "Faqueiro 101 peças", "valor": 705.04, "foto": "images/presentes/faqueiro-101.webp"},
    {"id": "aparelho-jantar-dourado", "categoria": "mesa", "nome": "Aparelho de jantar com filete dourado", "valor": 1691.86, "foto": "images/presentes/aparelho-jantar-dourado.webp"},
    {"id": "faqueiro-84", "categoria": "mesa", "nome": "Faqueiro 84 peças", "valor": 1835.77, "foto": "images/presentes/faqueiro-84.webp"},
    {"id": "colher-de-pau", "categoria": "cozinha", "nome": "Colher de pau", "valor": 33.46, "foto": "images/presentes/colher-de-pau.webp"},
    {"id": "pano-de-prato", "categoria": "cozinha", "nome": "Pano de prato", "valor": 36.89, "foto": "images/presentes/pano-de-prato.webp"},
    {"id": "forma-pudim", "categoria": "cozinha", "nome": "Forma de pudim", "valor": 57.45, "foto": "images/presentes/forma-pudim.webp"},
    {"id": "potes-hermeticos", "categoria": "cozinha", "nome": "Potes herméticos", "valor": 66.59, "foto": "images/presentes/potes-hermeticos.webp"},
    {"id": "porta-condimentos", "categoria": "cozinha", "nome": "Porta-condimentos com suporte", "valor": 82.58, "foto": "images/presentes/porta-condimentos.webp"},
    {"id": "utensilios-cozinha", "categoria": "cozinha", "nome": "Kit de utensílios de madeira e silicone", "valor": 118.93, "foto": "images/presentes/utensilios-cozinha.webp"},
    {"id": "garrafa-termica", "categoria": "cozinha", "nome": "Garrafa térmica", "valor": 129.9, "foto": "images/presentes/garrafa-termica.webp"},
    {"id": "assadeiras-vidro", "categoria": "cozinha", "nome": "Assadeiras de vidro Marinex (4 peças)", "valor": 146.42, "foto": "images/presentes/assadeiras-vidro.webp"},
    {"id": "frigideira", "categoria": "cozinha", "nome": "Frigideira antiaderente", "valor": 149.9, "foto": "images/presentes/frigideira.webp"},
    {"id": "escorredor", "categoria": "cozinha", "nome": "Escorredor de louça", "valor": 179.9, "foto": "images/presentes/escorredor.webp"},
    {"id": "lixeira-pedal", "categoria": "cozinha", "nome": "Lixeira com pedal", "valor": 179.9, "foto": "images/presentes/lixeira-pedal.webp"},
    {"id": "facas-churrasco", "categoria": "cozinha", "nome": "Jogo de facas de churrasco", "valor": 189.9, "foto": "images/presentes/facas-churrasco.webp"},
    {"id": "panela-pressao", "categoria": "cozinha", "nome": "Panela de pressão", "valor": 229.99, "foto": "images/presentes/panela-pressao.webp"},
    {"id": "travessas-lasanha", "categoria": "cozinha", "nome": "Travessas refratárias Oxford para lasanha", "valor": 249.32, "foto": "images/presentes/travessas-lasanha.webp"},
    {"id": "wok", "categoria": "cozinha", "nome": "Wok", "valor": 259.9, "foto": "images/presentes/wok.webp"},
    {"id": "facas-cepo", "categoria": "cozinha", "nome": "Jogo de facas com cepo", "valor": 389.99, "foto": "images/presentes/facas-cepo.webp"},
    {"id": "panelas-tramontina", "categoria": "cozinha", "nome": "Jogo de panelas Tramontina Solar (6 peças)", "valor": 705.04, "foto": "images/presentes/panelas-tramontina.webp"},
    {"id": "cafeteira", "categoria": "eletros", "nome": "Cafeteira Cadence Single Colors vermelha (110 V)", "valor": 78.01, "foto": "images/presentes/cafeteira.webp"},
    {"id": "liquidificador", "categoria": "eletros", "nome": "Liquidificador", "valor": 143.11, "foto": "images/presentes/liquidificador.webp"},
    {"id": "chaleira-eletrica", "categoria": "eletros", "nome": "Chaleira elétrica", "valor": 144.9, "foto": "images/presentes/chaleira-eletrica.webp"},
    {"id": "ferro-vapor", "categoria": "eletros", "nome": "Ferro de passar a vapor", "valor": 149.9, "foto": "images/presentes/ferro-vapor.webp"},
    {"id": "sanduicheira", "categoria": "eletros", "nome": "Sanduicheira e grill", "valor": 152.9, "foto": "images/presentes/sanduicheira.webp"},
    {"id": "batedeira", "categoria": "eletros", "nome": "Batedeira Philco 4 velocidades", "valor": 157.96, "foto": "images/presentes/batedeira.webp"},
    {"id": "mixer", "categoria": "eletros", "nome": "Mixer 3 em 1", "valor": 234.9, "foto": "images/presentes/mixer.webp"},
    {"id": "panela-arroz", "categoria": "eletros", "nome": "Panela elétrica de arroz", "valor": 239.9, "foto": "images/presentes/panela-arroz.webp"},
    {"id": "torradeira", "categoria": "eletros", "nome": "Torradeira Ford 2 fatias inox", "valor": 249.21, "foto": "images/presentes/torradeira.webp"},
    {"id": "air-fryer", "categoria": "eletros", "nome": "Fritadeira air fryer", "valor": 316.72, "foto": "images/presentes/air-fryer.webp"},
    {"id": "aspirador-vertical", "categoria": "eletros", "nome": "Aspirador de pó vertical", "valor": 409.9, "foto": "images/presentes/aspirador-vertical.webp"},
    {"id": "purificador", "categoria": "eletros", "nome": "Purificador de água Electrolux com painel touch", "valor": 555.24, "foto": "images/presentes/purificador.webp"},
    {"id": "micro-ondas", "categoria": "eletros", "nome": "Micro-ondas Philco 25 litros", "valor": 591.97, "foto": "images/presentes/micro-ondas.webp"},
    {"id": "cafeteira-expresso", "categoria": "eletros", "nome": "Cafeteira expresso", "valor": 649.9, "foto": "images/presentes/cafeteira-expresso.webp"},
    {"id": "forno-eletrico", "categoria": "eletros", "nome": "Forno elétrico", "valor": 1207.59, "foto": "images/presentes/forno-eletrico.webp"},
    {"id": "robo-aspirador", "categoria": "eletros", "nome": "Robô aspirador", "valor": 1249.9, "foto": "images/presentes/robo-aspirador.webp"},
    {"id": "lavadora", "categoria": "eletros", "nome": "Lavadora de roupas Brastemp Ative! 11 kg", "valor": 1473.71, "foto": "images/presentes/lavadora.webp"},
    {"id": "ar-condicionado", "categoria": "eletros", "nome": "Ar-condicionado split LG Inverter 11.500 BTUs quente/frio", "valor": 2190.98, "foto": "images/presentes/ar-condicionado.webp"},
    {"id": "smart-tv", "categoria": "eletros", "nome": "Smart TV Samsung 42 polegadas", "valor": 2190.98, "foto": "images/presentes/smart-tv.webp"},
    {"id": "lava-loucas", "categoria": "eletros", "nome": "Lava-louças de piso", "valor": 3061.29, "foto": "images/presentes/lava-loucas.webp"},
    {"id": "lava-e-seca", "categoria": "eletros", "nome": "Lava e seca Brastemp", "valor": 3218.91, "foto": "images/presentes/lava-e-seca.webp"},
    {"id": "geladeira", "categoria": "eletros", "nome": "Geladeira", "valor": 3276.01, "foto": "images/presentes/geladeira.webp"},
    {"id": "porta-chaves", "categoria": "casa", "nome": "Porta-chaves", "valor": 82.58, "foto": "images/presentes/porta-chaves.webp"},
    {"id": "cesto-de-roupa", "categoria": "casa", "nome": "Cesto de roupa", "valor": 99.71, "foto": "images/presentes/cesto-de-roupa.webp"},
    {"id": "mesa-multiuso", "categoria": "casa", "nome": "Mesa multiuso Tramontina preta", "valor": 111.13, "foto": "images/presentes/mesa-multiuso.webp"},
    {"id": "cabides-flocados", "categoria": "casa", "nome": "Kit de cabides flocados", "valor": 119.7, "foto": "images/presentes/cabides-flocados.webp"},
    {"id": "travesseiros", "categoria": "casa", "nome": "Par de travesseiros", "valor": 179.8, "foto": "images/presentes/travesseiros.webp"},
    {"id": "abajur", "categoria": "casa", "nome": "Abajur para o quarto", "valor": 199.9, "foto": "images/presentes/abajur.webp"},
    {"id": "rotuladora", "categoria": "casa", "nome": "Rotuladora eletrônica Brother PT-80", "valor": 213.92, "foto": "images/presentes/rotuladora.webp"},
    {"id": "jogo-de-banho", "categoria": "casa", "nome": "Jogo de banho gigante", "valor": 219.63, "foto": "images/presentes/jogo-de-banho.webp"},
    {"id": "roupoes", "categoria": "casa", "nome": "Par de roupões", "valor": 258, "foto": "images/presentes/roupoes.webp"},
    {"id": "edredom-queen", "categoria": "casa", "nome": "Edredom queen", "valor": 299, "foto": "images/presentes/edredom-queen.webp"},
    {"id": "lencol-queen", "categoria": "casa", "nome": "Jogo de lençol queen", "valor": 299, "foto": "images/presentes/lencol-queen.webp"},
    {"id": "kit-banheiro", "categoria": "casa", "nome": "Conjunto de acessórios para banheiro", "valor": 325.85, "foto": "images/presentes/kit-banheiro.webp"},
    {"id": "tapete-sala", "categoria": "casa", "nome": "Tapete para a sala", "valor": 479.9, "foto": "images/presentes/tapete-sala.webp"},
    {"id": "cota-cama", "categoria": "casa", "nome": "Cota para a cama nova", "valor": 500, "foto": "images/presentes/cota-cama.webp"},
    {"id": "cota-sofa", "categoria": "casa", "nome": "Cota para o sofá novo", "valor": 500, "foto": "images/presentes/cota-sofa.webp"},
    {"id": "cristaleira", "categoria": "casa", "nome": "Cristaleira", "valor": 934.62, "foto": "images/presentes/cristaleira.webp"},
    {"id": "div-dormir-ate-tarde", "categoria": "divertidos", "nome": "Dormir até meio-dia depois da festa", "valor": 50, "foto": "images/presentes/div-dormir-ate-tarde.webp"},
    {"id": "div-pastel-feira", "categoria": "divertidos", "nome": "Pastel e caldo de cana na feira", "valor": 60, "foto": "images/presentes/div-pastel-feira.webp"},
    {"id": "div-pipoca-filme", "categoria": "divertidos", "nome": "Pipoca e filme no primeiro domingo", "valor": 60, "foto": "images/presentes/div-pipoca-filme.webp"},
    {"id": "div-chocolate-pazes", "categoria": "divertidos", "nome": "Chocolate para as pazes da primeira briga", "valor": 70, "foto": "images/presentes/div-chocolate-pazes.webp"},
    {"id": "div-pizza-casa-nova", "categoria": "divertidos", "nome": "A pizza da primeira noite na casa nova", "valor": 80, "foto": "images/presentes/div-pizza-casa-nova.webp"},
    {"id": "div-cafe-segundas", "categoria": "divertidos", "nome": "O café de toda segunda-feira", "valor": 90, "foto": "images/presentes/div-cafe-segundas.webp"},
    {"id": "div-chuveiro-queimado", "categoria": "divertidos", "nome": "Para o primeiro chuveiro queimado", "valor": 110, "foto": "images/presentes/div-chuveiro-queimado.webp"},
    {"id": "div-kit-ressaca", "categoria": "divertidos", "nome": "Kit ressaca para o dia seguinte", "valor": 120, "foto": "images/presentes/div-kit-ressaca.webp"},
    {"id": "div-volta-da-festa", "categoria": "divertidos", "nome": "A volta para casa depois da festa", "valor": 130, "foto": "images/presentes/div-volta-da-festa.webp"},
    {"id": "div-louca", "categoria": "divertidos", "nome": "Para nunca brigarem por causa da louça", "valor": 140, "foto": "images/presentes/div-louca.webp"},
    {"id": "div-vinho-1-ano", "categoria": "divertidos", "nome": "O vinho do primeiro aniversário", "valor": 150, "foto": "images/presentes/div-vinho-1-ano.webp"},
    {"id": "div-churrasco", "categoria": "divertidos", "nome": "Churrasco de inauguração da casa", "valor": 170, "foto": "images/presentes/div-churrasco.webp"},
    {"id": "div-conta-de-luz", "categoria": "divertidos", "nome": "A conta de luz do primeiro mês", "valor": 180, "foto": "images/presentes/div-conta-de-luz.webp"},
    {"id": "div-faxina", "categoria": "divertidos", "nome": "Faxina depois da mudança", "valor": 180, "foto": "images/presentes/div-faxina.webp"},
    {"id": "div-aula-culinaria", "categoria": "divertidos", "nome": "Aula de culinária para os noivos", "valor": 190, "foto": "images/presentes/div-aula-culinaria.webp"},
    {"id": "div-sem-cozinhar", "categoria": "divertidos", "nome": "Um fim de semana sem cozinhar", "valor": 220, "foto": "images/presentes/div-sem-cozinhar.webp"},
    {"id": "div-series-filmes", "categoria": "divertidos", "nome": "Um ano de séries e filmes", "valor": 240, "foto": "images/presentes/div-series-filmes.webp"},
    {"id": "div-montar-moveis", "categoria": "divertidos", "nome": "Montar os móveis sem nenhuma briga", "valor": 250, "foto": "images/presentes/div-montar-moveis.webp"},
    {"id": "div-jantar-1-mes", "categoria": "divertidos", "nome": "O jantar de um mês de casados", "valor": 260, "foto": "images/presentes/div-jantar-1-mes.webp"},
    {"id": "div-mercado", "categoria": "divertidos", "nome": "A primeira compra de mercado", "valor": 300, "foto": "images/presentes/div-mercado.webp"},
    {"id": "div-mudanca", "categoria": "divertidos", "nome": "O caminhão da mudança", "valor": 380, "foto": "images/presentes/div-mudanca.webp"},
    {"id": "div-festa-1-ano", "categoria": "divertidos", "nome": "A festa de um ano de casados", "valor": 500, "foto": "images/presentes/div-festa-1-ano.webp"},
    {"id": "teste-pix", "categoria": "casa", "nome": "Teste de pagamento", "descricao": "Só aparece com ?teste=1 no endereço. Aceita apenas PIX.", "valor": 1, "oculto": true, "somentePix": true}
  ]
});
